4 TO - DO - Task
Please complete all the problem listed below.
4.1 Warming Up Exercise: Basic Vector and Matrix Operation with Numpy.
Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
import numpy as np

# Question 1
empty_array = np.empty((2, 2))
print("Initializing an empty array of size 2x2:\n",empty_array)


# Question 2
ones_array = np.ones((4, 2))
print("\nAll-Ones Array of size 4x2:\n", ones_array)


# Question 3
fill_value_array = np.full((3, 3), 7)
print("\nArray Filled with Value 10 (2x2):\n",fill_value_array)


# Question 4
given_array = np.array([[1, 2], [3, 4]])
zeros_like_array = np.zeros_like(given_array)
print("\nZeros Array (Same Shape as Given Array):\n",zeros_like_array)



# Question 5
ones_like_array = np.ones_like(given_array)
print("\nOnes Array (Same Shape as Given Array):\n",ones_like_array)


# Question 6
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\nConverted List to Numpy Array:\n", numpy_array)


Initializing an empty array of size 2x2:
 [[5.01960171e-310 0.00000000e+000]
 [9.04115220e+271 1.02124020e+277]]

All-Ones Array of size 4x2:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Array Filled with Value 10 (2x2):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros Array (Same Shape as Given Array):
 [[0 0]
 [0 0]]

Ones Array (Same Shape as Given Array):
 [[1 1]
 [1 1]]

Converted List to Numpy Array:
 [1 2 3 4]


4.1.1 Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
import numpy as np

#Question 1
array = np.arange(10, 50)
print("An array with values ranging from 10 to 49:\n",array)

#Question 2
matrix = np.arange(9).reshape(3, 3)
print("\n 3*3 Matrix with values ranging from 0 to 8:\n",matrix)

#Question 3
idemtity_matrix = np.eye(3)
print("\n 3*3 Identity matrix:\n",idemtity_matrix)

#Question 4
random_array = np.random.random(30)
mean_value = array.mean()
print("\n Random array of size 30:\n",random_array)
print("\n The mean of the array:\n", mean_value)

#Question 5
array_with_value = np.random.random((10, 10))
min_value = array_with_value.min()
max_value = array_with_value.max()
print("\nThe minimum value is:\n", min_value)
print("The maximum value is:\n", max_value)

#Question 6
zero_array = np.zeros(10)
zero_array[4] = 1
print("\nZero Array with 5th element replaced:\n", zero_array)

#Question 7
arr = [1, 2, 0, 0, 4, 0]
reversed_arr = arr[::-1]
print("\n The reversed Array:\n", reversed_arr)

#Question 8
n = 4
border_array = np.ones((n, n), dtype=int)
border_array[1:-1, 1:-1] = 0
print("\n2D Array with Border:\n", border_array)

#Question 9
checker_board = np.zeros((8, 8), dtype=int)
checker_board[::2, ::2] = 1
checker_board[1::2, 1::2] = 1
print("\nCheckerboard Pattern:\n", checker_board)


An array with values ranging from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

 3*3 Matrix with values ranging from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

 3*3 Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

 Random array of size 30:
 [0.7443369  0.5155156  0.63084041 0.33717665 0.83019385 0.58173044
 0.64937381 0.15767588 0.2685413  0.96533437 0.30448076 0.01372834
 0.20407431 0.29397017 0.33866686 0.1294228  0.57352631 0.46321533
 0.59072917 0.2705004  0.20811124 0.4839409  0.96661279 0.59032666
 0.37160852 0.02043412 0.57155798 0.85847852 0.55060656 0.13758132]

 The mean of the array:
 29.5

The minimum value is:
 0.0016654104759067367
The maximum value is:
 0.9996539645286664

Zero Array with 5th element replaced:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

 The reversed Array:
 [0, 4, 0, 0, 2, 1]

2D Array with Border:
 [[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]

Checkerboard Pattern:
 [[1 0 

Problem - 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11, 12])

#Question 1
sum = x + y
print("The sum of two arrays x and y:\n",sum)

#Question 2
diff = x - y
print("\n The difference of two arrays x and y:\n",diff)

#Question 3
mult1 = x * 5
print("\n The multiplication of x with 5 is:\n",mult1)

#Question 4
square1 = x ** 2
print("\n The square of x is:\n",square1)

#Question 5
v_dot_w = np.dot(v,w)
x_dot_v = np.dot(x,v)
x_dot_y = np.dot(x, y)
print("\n The dot product of v and w:", v_dot_w)
print("\n The dot product of x and v:\n", x_dot_v)
print("\n The dot product of x and y:\n", x_dot_y)

#Question 6
xy_row_concat = np.concatenate((x, y), axis=0)
vw_col_concat = np.hstack((v,w))
print("\n The concatenate x and y along rows:\n", xy_row_concat)
print("\n The concatenate v and w along columns:\n", vw_col_concat)

#Questionn 7
try:
    xv_concat = np.concatenate((x, v), axis=0)
    print("\n The concatenation of x and v:\n", xv_concat)
except ValueError as e:
    print("\nError concatenating x and v:\n", e)



The sum of two arrays x and y:
 [[ 6  8]
 [10 13]]

 The difference of two arrays x and y:
 [[-4 -4]
 [-4 -3]]

 The multiplication of x with 5 is:
 [[ 5 10]
 [15 25]]

 The square of x is:
 [[ 1  4]
 [ 9 25]]

 The dot product of v and w: 219

 The dot product of x and v:
 [29 77]

 The dot product of x and y:
 [[19 22]
 [50 58]]

 The concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

 The concatenate v and w along columns:
 [ 9 10 11 12]

Error concatenating x and v:
 all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


Problem - 4: Matrix Operations:
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT
.

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

In [ ]:
import numpy as np
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

#Question 1
A_inv = np.linalg.inv(A)
I = np.dot(A, A_inv)
print("\nA.A^-1:\n", I)

#Question 2
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\nAB:\n", AB)
print("\nBA:\n", BA)
print("\nAB ≠ BA:", not np.array_equal(AB, BA))

#Question 3
AB_transpose = AB.transpose()
B_transpose = B.transpose()
A_transpose = A.transpose()
BT_AT = np.dot(B_transpose, A_transpose)
print("\n(AB)ᵀ:\n", AB_transpose)
print("\nBᵀAᵀ:\n", BT_AT)
print("\n(AB)ᵀ = BᵀAᵀ:", np.array_equal(AB_transpose, BT_AT))



A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B = np.array([-1, -3, 9])


# Using inverse method
X = np.dot(np.linalg.inv(A), B)
print("\nSolution using inverse method:\n", X)

# Using np.linalg.solve
X_solve = np.linalg.solve(A,B)
print("\nSolution using np.linalg.solve:\n", X_solve)


A.A^-1:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

AB:
 [[23 13]
 [51 29]]

BA:
 [[36 44]
 [13 16]]

AB ≠ BA: True

(AB)ᵀ:
 [[23 51]
 [13 29]]

BᵀAᵀ:
 [[23 51]
 [13 29]]

(AB)ᵀ = BᵀAᵀ: True

Solution using inverse method:
 [ 2.  1. -2.]

Solution using np.linalg.solve:
 [ 2.  1. -2.]


In [10]:
import numpy as np
import time


# 1. Element-wise Addition
size = 1000000
list1 = list(range(size))
list2 = list(range(size))
array1 = np.array(list1)
array2 = np.array(list2)


start_time = time.time()
list_sum = [x + y for x, y in zip(list1, list2)]
end_time = time.time()
print("List element-wise addition time:", end_time - start_time)




start_time = time.time()
array_sum = array1 + array2
end_time = time.time()
print("Numpy element-wise addition time:", end_time - start_time)


# 2. Element-wise Multiplication
start_time = time.time()
list_mult = [x * y for x, y in zip(list1, list2)]
end_time = time.time()
print("List element-wise multiplication time:", end_time - start_time)




start_time = time.time()
array_mult = array1 * array2
end_time = time.time()
print("Numpy element-wise multiplication time:", end_time - start_time)




# 3. Dot Product
start_time = time.time()
dot_product_list = sum(x * y for x, y in zip(list1, list2))
end_time = time.time()
print("List dot product time:", end_time - start_time)


start_time = time.time()
dot_product_array = np.dot(array1, array2)
end_time = time.time()
print("Numpy dot product time:", end_time - start_time)


# 4. Matrix Multiplication
size = 1000


# Using Python lists
matrix1 = [[j for j in range(size)] for i in range(size)]
matrix2 = [[j for j in range(size)] for i in range(size)]


start_time = time.time()
result_matrix = [[sum(matrix1[i][k] * matrix2[k][j] for k in
range(size)) for j in range(size)] for i in range(size)]
end_time = time.time()
print("Python list matrix multiplication time:", end_time - start_time)


# Using NumPy arrays
matrix1_np = np.array(matrix1)
matrix2_np = np.array(matrix2)


start_time = time.time()
result_matrix_np = np.dot(matrix1_np, matrix2_np)
end_time = time.time()


print("NumPy matrix multiplication time:", end_time - start_time)


List element-wise addition time: 0.0883641242980957
Numpy element-wise addition time: 0.0023610591888427734
List element-wise multiplication time: 0.10605120658874512
Numpy element-wise multiplication time: 0.0023398399353027344
List dot product time: 0.12258052825927734
Numpy dot product time: 0.0019800662994384766
Python list matrix multiplication time: 246.02623748779297
NumPy matrix multiplication time: 3.138439178466797
